# Web Scraping of TravelTriangle.com

In [1]:
import requests
from bs4 import BeautifulSoup
import re
import numpy as np
import pandas as pd
import warnings 
warnings.simplefilter('ignore', category=FutureWarning)

In [2]:
https://traveltriangle.com/tour-packages/india/page/2

SyntaxError: invalid syntax (4075035483.py, line 1)

In [3]:
packages=[]
package_names = []
Days =[]
discount=[]
Price= []
Actual_Price = []
cities= []
Cities_names=[]
hotel= []
pattern="(\d+)% Off"
pattern2="â\x82¹\s?([\d,]+)"
pattern3= "â\x82¹\s?([\d,]+)"
pattern4= "([A-Za-z\s]+)"
for i in range(1,40):
    url = f"https://traveltriangle.com/tour-packages/india/page/{i}"
    print (url)
    page=requests.get(url)
    soup=BeautifulSoup(page.text)
    packages=[]
    for i in soup.find_all("span",class_="fw9 m0 f16 pfc3"):
       packages.append(i.text)
    for package in packages:
        cleaned_name = re.sub(r"(?:From .+|For .+|: .+|Go on .+|Discover .+)", "", package).strip()
        if cleaned_name == "":
            package_names.append(np.nan)  # Pandas NA for missing values
        else:
            package_names.append(cleaned_name)
    for i in soup.find_all("span",class_="iblock sfc6"):
        Days.append(i.text)

    for i in soup.find_all("span",class_="f12 fw4 pt2 pb2 pl8 pr8 radius20 pbc1 sfcw at_discount_label"):
        regex=re.findall(pattern,i.text)
        if len(regex) >0:
            discount.append(regex[0])
        else:
            discount.append(np.nan)

    for i in soup.find_all("h4",class_="sfc3 m0 f24 fw9 priceVal at_newprice"):
        regex=re.findall(pattern2,i.text)
        if len(regex) >0:
            price = int(regex[0].replace(",", ""))
            Price.append(price)
        else:
            Price.append(np.nan)
    for i in soup.find_all("h4", itemprop="priceSpecification"):
        regex = re.findall(pattern3, i.text)  # Find all matched prices
        if len(regex) > 1:  # Ensure there are at least two prices in the list
            second_price = regex[1]  # Get the second price
            second_price_clean = int(second_price.replace(",", ""))  # Remove commas and convert to integer
            Actual_Price.append(second_price_clean)
        else:
            Actual_Price.append(np.nan)

    for i in soup.find_all("ul",class_="clearfix package-cities-list at_packagecity_list"):
        cities.append(i.text)
        Cities_names = [line.split(' ')[0] for line in cities]

    for i in soup.find_all("div", class_="flex alignCenter"):
        text = i.text.strip()  # Get the text and remove leading/trailing whitespace
        if text:  # If text is present, append it
            hotel.append(text)
        else:  # If text is empty, append NaN
            hotel.append(np.nan)

<>:10: SyntaxWarning: invalid escape sequence '\d'
<>:11: SyntaxWarning: invalid escape sequence '\s'
<>:12: SyntaxWarning: invalid escape sequence '\s'
<>:13: SyntaxWarning: invalid escape sequence '\s'
<>:10: SyntaxWarning: invalid escape sequence '\d'
<>:11: SyntaxWarning: invalid escape sequence '\s'
<>:12: SyntaxWarning: invalid escape sequence '\s'
<>:13: SyntaxWarning: invalid escape sequence '\s'
C:\Users\lenovo slim 3\AppData\Local\Temp\ipykernel_13480\4017566993.py:10: SyntaxWarning: invalid escape sequence '\d'
  pattern="(\d+)% Off"
C:\Users\lenovo slim 3\AppData\Local\Temp\ipykernel_13480\4017566993.py:11: SyntaxWarning: invalid escape sequence '\s'
  pattern2="â\x82¹\s?([\d,]+)"
C:\Users\lenovo slim 3\AppData\Local\Temp\ipykernel_13480\4017566993.py:12: SyntaxWarning: invalid escape sequence '\s'
  pattern3= "â\x82¹\s?([\d,]+)"
C:\Users\lenovo slim 3\AppData\Local\Temp\ipykernel_13480\4017566993.py:13: SyntaxWarning: invalid escape sequence '\s'
  pattern4= "([A-Za-z\s]+)"

https://traveltriangle.com/tour-packages/india/page/1
https://traveltriangle.com/tour-packages/india/page/2
https://traveltriangle.com/tour-packages/india/page/3
https://traveltriangle.com/tour-packages/india/page/4
https://traveltriangle.com/tour-packages/india/page/5
https://traveltriangle.com/tour-packages/india/page/6
https://traveltriangle.com/tour-packages/india/page/7
https://traveltriangle.com/tour-packages/india/page/8
https://traveltriangle.com/tour-packages/india/page/9
https://traveltriangle.com/tour-packages/india/page/10
https://traveltriangle.com/tour-packages/india/page/11
https://traveltriangle.com/tour-packages/india/page/12
https://traveltriangle.com/tour-packages/india/page/13
https://traveltriangle.com/tour-packages/india/page/14
https://traveltriangle.com/tour-packages/india/page/15
https://traveltriangle.com/tour-packages/india/page/16
https://traveltriangle.com/tour-packages/india/page/17
https://traveltriangle.com/tour-packages/india/page/18
https://traveltriangle.com/tour-packages/india/page/19
https://traveltriangle.com/tour-packages/india/page/20
https://traveltriangle.com/tour-packages/india/page/21
https://traveltriangle.com/tour-packages/india/page/22
https://traveltriangle.com/tour-packages/india/page/23
https://traveltriangle.com/tour-packages/india/page/24
https://traveltriangle.com/tour-packages/india/page/25
https://traveltriangle.com/tour-packages/india/page/26
https://traveltriangle.com/tour-packages/india/page/27
https://traveltriangle.com/tour-packages/india/page/28
https://traveltriangle.com/tour-packages/india/page/29
https://traveltriangle.com/tour-packages/india/page/30
https://traveltriangle.com/tour-packages/india/page/31
https://traveltriangle.com/tour-packages/india/page/32
https://traveltriangle.com/tour-packages/india/page/33
https://traveltriangle.com/tour-packages/india/page/34
https://traveltriangle.com/tour-packages/india/page/35
https://traveltriangle.com/tour-packages/india/page/36
https://traveltriangle.com/tour-packages/india/page/37
https://traveltriangle.com/tour-packages/india/page/38
https://traveltriangle.com/tour-packages/india/page/39

In [4]:
df = pd.DataFrame({"Package Name": package_names,"No.OF_Days":Days,"Actual_price":Actual_Price,"Package_Price":Price,"City":Cities_names,"Other_City":cities})
df["Discount_amt"] = df["Actual_price"] - df["Package_Price"]

# Print the DataFrame
df

,Package Name,No.OF_Days,Actual_price,Package_Price,City,Other_City,Discount_amt
0,Most Reasonable Goa Honeymoon Tour Packages,5 Days & 4 Nights,9142.0,7999,Goa,Goa (5D),1143.0
1,Fantastic Andaman Honeymoon Package,5 Days & 4 Nights,18811.0,15599,Port,Port Blair (3D)Havelock (2D),3212.0
2,Romantic Mussoorie Tour Package,3 Days & 2 Nights,12000.0,10500,Mussoorie,Mussoorie (3D),1500.0
3,Coorg Package,3 Days & 2 Nights,15934.0,14500,Coorg,Coorg (3D),1434.0
4,Best 4N 5D Andaman Sightseeing Tour Package,5 Days & 4 Nights,36484.0,33200,Port,Port Blair (4D)Havelock (1D),3284.0
...,...,...,...,...,...,...,...
970,Best Selling Varanasi Package,3 Days & 2 Nights,16129.0,15000,Varanasi,Varanasi (3D),1129.0
971,Lonavala Mahabaleshwar Tour Package,4 Days & 3 Nights,19780.0,18000,Mahabaleshwar,Mahabaleshwar (2D)Lonavala (2D),1780.0
972,Pleasurable Kasauli Sightseeing Tour Package,3 Days & 2 Nights,26901.0,24480,Kasauli,Kasauli (3D),2421.0
973,Mesmeric Mount Abu Honeymoon Package,2 Days & 1 Nights,7692.0,7000,Mount,Mount Abu (2D),692.0
974,Delightful Delhi Honeymoon Package,4 Days & 3 Nights,19780.0,18000,New,New Delhi (1D)Agra (1D)Jaipur (2D),1780.0

In [5]:
df.to_excel("cities.xlsx", index=False)

In [24]:
l=[]
links = []
for i in range(1,40):
    url = f"https://traveltriangle.com/tour-packages/india/page/{i}"
    print (url)
    page=requests.get(url)
    soup=BeautifulSoup(page.text)
    for i in soup.find_all('a'):
        if i.has_attr('href'):
            if len(re.findall("\/packages.*\d$",i['href']))>0:
                l.append(re.findall("\/packages.*\d$",i['href'])[0])
    for i in l:
        links.append("https://traveltriangle.com"+i)

<>:10: SyntaxWarning: invalid escape sequence '\/'
<>:11: SyntaxWarning: invalid escape sequence '\/'
<>:10: SyntaxWarning: invalid escape sequence '\/'
<>:11: SyntaxWarning: invalid escape sequence '\/'
C:\Users\lenovo slim 3\AppData\Local\Temp\ipykernel_10408\2705282067.py:10: SyntaxWarning: invalid escape sequence '\/'
  if len(re.findall("\/packages.*\d$",i['href']))>0:
C:\Users\lenovo slim 3\AppData\Local\Temp\ipykernel_10408\2705282067.py:11: SyntaxWarning: invalid escape sequence '\/'
  l.append(re.findall("\/packages.*\d$",i['href'])[0])

https://traveltriangle.com/tour-packages/india/page/1
https://traveltriangle.com/tour-packages/india/page/2
https://traveltriangle.com/tour-packages/india/page/3
https://traveltriangle.com/tour-packages/india/page/4
https://traveltriangle.com/tour-packages/india/page/5
https://traveltriangle.com/tour-packages/india/page/6
https://traveltriangle.com/tour-packages/india/page/7
https://traveltriangle.com/tour-packages/india/page/8
https://traveltriangle.com/tour-packages/india/page/9
https://traveltriangle.com/tour-packages/india/page/10
https://traveltriangle.com/tour-packages/india/page/11
https://traveltriangle.com/tour-packages/india/page/12
https://traveltriangle.com/tour-packages/india/page/13
https://traveltriangle.com/tour-packages/india/page/14
https://traveltriangle.com/tour-packages/india/page/15
https://traveltriangle.com/tour-packages/india/page/16
https://traveltriangle.com/tour-packages/india/page/17
https://traveltriangle.com/tour-packages/india/page/18
https://traveltriangle.com/tour-packages/india/page/19
https://traveltriangle.com/tour-packages/india/page/20
https://traveltriangle.com/tour-packages/india/page/21
https://traveltriangle.com/tour-packages/india/page/22
https://traveltriangle.com/tour-packages/india/page/23
https://traveltriangle.com/tour-packages/india/page/24
https://traveltriangle.com/tour-packages/india/page/25
https://traveltriangle.com/tour-packages/india/page/26
https://traveltriangle.com/tour-packages/india/page/27
https://traveltriangle.com/tour-packages/india/page/28
https://traveltriangle.com/tour-packages/india/page/29
https://traveltriangle.com/tour-packages/india/page/30
https://traveltriangle.com/tour-packages/india/page/31
https://traveltriangle.com/tour-packages/india/page/32
https://traveltriangle.com/tour-packages/india/page/33
https://traveltriangle.com/tour-packages/india/page/34
https://traveltriangle.com/tour-packages/india/page/35
https://traveltriangle.com/tour-packages/india/page/36
https://traveltriangle.com/tour-packages/india/page/37
https://traveltriangle.com/tour-packages/india/page/38
https://traveltriangle.com/tour-packages/india/page/39

In [27]:
len(links)

59280

In [28]:
newlink=list(set(links))

In [29]:
len(newlink)

978

In [75]:
rate= []
total_traveled=[]
for i in newlink:
    page1=requests.get(i)
    soup1=BeautifulSoup(page1.text)
    for i in soup1.find_all("p",class_="f12 at_package_count"):
        rate.append(i.text)
    for i in soup1.find_all("p",class_="pfc4 f12 text-center m8"):
        total_traveled.append(i.text)

In [76]:
Rate=[]
for item in rate:
    match = re.search(r"Rated (\d\.\d)", item)
    if match:
        Rate.append (match.group(1))
        #print(f"Rated: {rated_score}")
    else:  # If text is empty, append NaN
        Rate.append(np.nan)

In [82]:
len(Rate)

976

In [85]:
served=[]
for item in total_traveled[0:976]:
    match = re.search(r"\d+", item)
    if match:
        served.append (int(match.group(0)))
        #print(f"Rated: {rated_score}")
    else:  # If text is empty, append NaN
        served.append(np.nan)

In [86]:
len(served)

976

In [72]:
served=[]
for item in total_traveled:
    match = re.search(r"\d+", item)
    if match:
        served.append (int(match.group(0)))
        #print(f"Rated: {rated_score}")
    else:  # If text is empty, append NaN
        served.append(np.nan)

In [73]:
served

[24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281,
 24281]

In [87]:
df1 = pd.DataFrame({"Rate": Rate,"Served_By_site":served})
df1

    Rate  Served_By_site
0    4.1           24281
1    NaN            6033
2    4.6            5258
3    4.1            6433
4    NaN            6033
..   ...             ...
971  4.1            6033
972  4.2           25920
973  NaN           13417
974  4.1           14178
975  4.1            6433

[976 rows x 2 columns]

In [88]:
result = pd.concat([df, df1], axis=1)
result

,Package Name,No.OF_Days,Actual_price,Package_Price,City,Discount_amt,Rate,Served_By_site
0,Most Reasonable Goa Honeymoon Tour Packages,5 Days & 4 Nights,9142.0,7999.0,Goa,1143.0,4.1,24281
1,Fantastic Andaman Honeymoon Package,5 Days & 4 Nights,18811.0,15599.0,Port,3212.0,NaN,6033
2,Romantic Mussoorie Tour Package,3 Days & 2 Nights,12000.0,10500.0,Mussoorie,1500.0,4.6,5258
3,Coorg Package,3 Days & 2 Nights,15934.0,14500.0,Coorg,1434.0,4.1,6433
4,Best 4N 5D Andaman Sightseeing Tour Package,5 Days & 4 Nights,36484.0,33200.0,Port,3284.0,NaN,6033
...,...,...,...,...,...,...,...,...
971,Lonavala Mahabaleshwar Tour Package,4 Days & 3 Nights,19780.0,18000.0,Mahabaleshwar,1780.0,4.1,6033
972,Pleasurable Kasauli Sightseeing Tour Package,3 Days & 2 Nights,26901.0,24480.0,Kasauli,2421.0,4.2,25920
973,Mesmeric Mount Abu Honeymoon Package,2 Days & 1 Nights,7692.0,7000.0,Mount,692.0,NaN,13417
974,Delightful Delhi Honeymoon Package,4 Days & 3 Nights,19780.0,18000.0,New,1780.0,4.1,14178
975,NaN,NaN,NaN,NaN,NaN,NaN,4.1,6433

In [89]:
result.to_excel("result.xlsx", index=False)